### ISSUE TITLE
solver behind spsolve

### ISSUE THREAD

**Issue by Oussamaaat** [cntaylor/factorGraph2DsatelliteExample#1]
Hello, thanks for providing the code and the tutorial paper, it is very interesting !

I have one question regarding the solver behind the spsolve function, in the documentation i read that it uses scikits.umfpack if installed but i don't see it in the requirements.yml which means you didn't use it ?

Also i'm a little bit suspicious about the results of spsolve (without umfpack) since i compared the results of delta_x in the first loop with a delta_x computed in Matlab using the backslash operator but the results are different, keeping the same tresholds it doesn't converge in matlab.

**Comment by cntaylor** [comment]
I use a conda environment on Windows and have whatever conda install scipy gives me.  I have not looked at using/not using umfpack.

How different were your delta_x results?  After making this example and using for a couple of years, I've come to realize that it is not as stable as most scenarios hopefully are.  There are evidently some singular values in the L matrix that are close to zero, so when you invert, it can be unstable.  I have run into this if the initialization is too far off, or some specific instances of the simulated results.  I have solved this in the past be comparing how much the residuals change for how much your state changes, and if it is too large, I just stop iterating.  That is not in this code though.

BTW, I assume you are talking about the orbitFG (full batch), and not sliding window, correct?  Are you using the same data in MATLAB, or did you create a different data file?

**Comment by cntaylor** [comment]
BTW, if your interest is just how to do a factor graph in MATLAB, I have an example I could share with you as well.  I would probably put it in a separate repository, but happy to do that if desired.

**Comment by Oussamaaat** [comment]
Thank you for your answer, yes i used the same data and orbitFG, for N = 5 for example i get for the first loop : 

delta_x (matlab) = 
    [1.255226648455023e+06, -1.482177648570547e+06, -2.836094667748766e+03, 2.336107624775841e+03, 
     1.212678236670389e+06, -1.447152511107610e+06, -2.837023098549756e+03, 2.333920922753792e+03
     1.170116051026471e+06, -1.412159713815140e+06, -2.837930369340339e+03, 2.331795498955980e+03
     1.127540413660796e+06, -1.377198342191389e+06, -2.838815885261668e+03, 2.329730729716495e+03
     1.084951655580295e+06, -1.342267491125026e+06, -2.839679058108624e+03, 2.327725986652627e+03]

delta_x (python) :
array([ 1.23643138e+06, -2.01523216e+07, -4.51839586e+03,  1.88933602e+05,
           1.16864827e+06, -1.73185339e+07, -4.51936100e+03,  1.88905461e+05,
           1.10085013e+06, -1.44851365e+07, -4.52038646e+03,  1.88881564e+05,
           1.03303638e+06, -1.16520658e+07, -4.52142929e+03,  1.88861910e+05,
           9.65207121e+05, -8.81925798e+06, -4.52244658e+03,  1.88846499e+05])

L and y are the same.

And yes i would like to see your version on Matlab as I'm trying to adapt the code to the gnss problem.

Thanks again

**Comment by cntaylor** [comment]
I would avoid small N values for this problem.  I've found them to be numerically unstable.  When N gets larger, the problem becomes more stable.  I think this makes sense as just a few measurements doesn't really have enough information to resolve the orbit (the distance away from the Earth).  I would suggest trying a much larger N (~1000?) and see what happens

**Comment by cntaylor** [comment]
I uploaded my MATLAB live script for a simple factor graph example at [this repo](https://github.com/cntaylor/simpleMatlabFactorGraph).  I am not on a computer with MATLAB, so I hope it still works, etc.  (Made this a few years ago).

**Comment by Oussamaaat** [comment]
After reviewing my code again, i noticed i had an error when updating the states, here are my final results running on all epochs, what do you think about the difference in delta_x between matlab and python  ? 

**In python :** 

```
iteration 1 delta_x length was 150292481.8079092 scale was 0.125
iteration 2 delta_x length was 135809760.7218694 scale was 0.125
iteration 3 delta_x length was 121725568.35251948 scale was 0.125
iteration 4 delta_x length was 108331043.98923689 scale was 0.125
iteration 5 delta_x length was 95823553.46860518 scale was 0.125
iteration 6 delta_x length was 84311678.88824603 scale was 0.125
iteration 7 delta_x length was 73864384.1061631 scale was 0.125
iteration 8 delta_x length was 129015276.7432608 scale was 0.25
iteration 9 delta_x length was 97218014.52029088 scale was 0.25
iteration 10 delta_x length was 72821726.839491 scale was 0.25
iteration 11 delta_x length was 109236438.27000587 scale was 0.5
iteration 12 delta_x length was 113179063.37394187 scale was 1
iteration 13 delta_x length was 24336485.82825001 scale was 1
iteration 14 delta_x length was 406353.73469825723 scale was 1
iteration 15 delta_x length was 132.2292253154986 scale was 1
iteration 16 delta_x length was 0.016576289101966957 scale was 1
```

**In matlab :**

```
Iteration 1 delta_x length was: 150291873.2793 scale was : 0.125
Iteration 2 delta_x length was: 135811191.7354 scale was : 0.125
Iteration 3 delta_x length was: 121726275.5581 scale was : 0.125
Iteration 4 delta_x length was: 108332237.8732 scale was : 0.125
Iteration 5 delta_x length was: 95822882.8977 scale was : 0.125
Iteration 6 delta_x length was: 84310718.0512 scale was : 0.125
Iteration 7 delta_x length was: 73863545.034 scale was : 0.125
Iteration 8 delta_x length was: 129013419.8958 scale was : 0.25
Iteration 9 delta_x length was: 97219087.3764 scale was : 0.25
Iteration 10 delta_x length was: 72821276.1835 scale was : 0.25
Iteration 11 delta_x length was: 109239935.5252 scale was : 0.5
Iteration 12 delta_x length was: 113174956.3986 scale was : 1
Iteration 13 delta_x length was: 24336732.9156 scale was : 1
Iteration 14 delta_x length was: 406357.1666 scale was : 1
Iteration 15 delta_x length was: 132.2931 scale was : 1
Iteration 16 delta_x length was: 0.013665 scale was : 1
```

I have other questions please and you can close the issue :
- what's the logic behind setting the conditions values `ratio < 4. and ratio > .25` `scale < .001` `assert(scale > 1E-6)` `la.norm(delta_x)<12 or num_iters > 100` is it problem dependent or it is related to the gauss newton algorithm ? 
- what would be the main differences between using a code like yours from scratch and gtsam especially for huge matrix problems like GNSS ?
- finally in your paper you add one row for the prior in the L matrix but in the code you don't ?

Thank you very much for your help, your time and the matlab code you provided, i really appreciate it !

Oussama

**Comment by cntaylor** [comment]
Lots of great questions.  I'll try to address them all here:
* Difference between Python and MATLAB.  Short answer: I don't know.  Long answer:  I have noticed that the sparse solver in Python (at least some versions) are approximate and not exact.  So I guess two different implementations lead to small differences.  That said, those two are really close together.

* Logic behind different conditions:
  * The `ratio` tests are pretty standard.  That is a way to test how valid your linear approximations are.  Whether doing a damped Gauss-Newton, dogleg, Levenburg-Marquardt, or some other trust region method, the question is when do you trust the step that the method is telling you to take.  This ratio test makes sure that your linear approximation and what happened are relatively close to each other.  Why 4 (1/4)?  That I don't know.  That is a number that seemed to show up in lots of papers and other things when I was looking at trust methods more closely.  This one is not problem dependent.
  * Scale is a result of the ratio test described above.  By the definition of a derivative, your linear approximation should be good for a small enough step.  So while the scale values here may be problem dependent, they are also very "loose".  In general, if your scale is becoming really small, it usually means your derivatives are wrong (they are not derivatives of the (negative) residual function).  This is more a debugging help than anything functional.  I guess it could vary with problem, but usually I use it until I know my derivatives are correct and then can just remove that part.  The `test_Jacobian` function is another debugging help but not needed to run the factor graph.
  * `la.norm(delta_x) < 12`  This one is problem dependent.  This tells you when you have converged.  Because you are talking about things out in space, if the total movement of all the satellite locations is 12m and there are about a thousand satellites positions you are optimizing over, you are talking about each positing moving about 1cm for distances from the earth in the "mega-meters".  For GNSS on the earth, that number would probably be something like 1E-3. 
  * `num_iters` is pretty universal (in my experience) and is just a fail safe for if your algorithm doesn't converge for some reason.  If you need more than 100 iterations to converge, I would worry about using a gradient based method to solve your problem in general.
* On comparing against GTSAM:  For understanding, I like rolling my own code.  I also find it easier to debug than GTSAM.  When you start moving into really large systems, GTSAM can handle the marginalization more cleanly than my sliding window code.  It is also in C++, so it is faster, etc.  
* On the prior factor.  I usually like avoiding priors if I can just because they are so often just "made up" numbers.  If you have enough data, it is not needed.  (Another reason you want a bigger "N" with this problem.)

**Comment by Oussamaaat** [comment]
Thank you very much Mr Clark, i really appreciate it, it is more clear now.
